version: '2'

services:
    feedbackdb:
        image: postgres:10.1
        restart: always
        volumes:
            - ./db/:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: feedbackdb
            POSTGRES_USER: uktrade
            POSTGRES_PASSWORD: uktrade
        ports:
            - "5432:5432"
