# Generated by Django 2.1.3 on 2019-01-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
